---
- name: find and store IPs of active containers
  hosts: localhost
  vars_files:
    - ./group_vars/all
  tasks:
  - name: remove inventory file if it exists
    ansible.builtin.file:
      path: ./inventory
      state: absent
    become: yes

  - name: create inventory file
    ansible.builtin.file:
      path: ./inventory
      state: touch
      mode: '0755'

  - name: create dynamic IP variable
    shell: bash ./get_container_dynamic_ip.sh
    register: dynamic_ip
    become: yes

  - set_fact:
      dynamic_ip={{ dynamic_ip.stdout }}

  - name: create static IP variable
    shell: bash ./get_container_static_ip.sh
    register: static_ip
    become: yes

  - set_fact:
      static_ip={{ static_ip.stdout }}

  - name: set IP values of jcb_static and jcb_dynamic containers
    ansible.builtin.blockinfile:
      path: ./inventory
      marker: ""
      block: |
        {{ dynamic_ip }}
        {{ static_ip }}
