---
- hosts: localhost 
  vars_prompt:
    - name: node_count
      prompt: enter desired amount of generated nodes
      default: 1000
      private: no
  tasks:
    - name: create temp config
      ansible.builtin.shell:
        cmd: cat ./volumes/config.ini > tempconfig.ini
    - name: edit temp config
      ansible.builtin.lineinfile:
        path: ./volumes/config.ini
        regexp: '^JCBDemo='
        line: JCBDemo={{ node_count }}
    - name: overwrite old config
      shell: bash "./scripts/overwrite_config.sh"
      become: yes
    - name: remove temp conf
      ansible.builtin.file:
        path: ./tempconfig.ini
        state: absent
      become: yes
