---
- hosts: localhost 
  tasks:
   - name: add container to inventory
     add_host:
       name: jcb_dynamic
       ansible_connection: docker
     changed_when: false
   - name: stop dynamic container
     community.docker.docker_container:
       name: jcb_dynamic
       state: stopped
   - name: re-run create container
     command: ansible-playbook create_containers.yml
     become: yes
