---
- hosts: localhost
  vars_prompt:
    - name: node_count
      prompt: enter desired amount of nodes
      default: 1000
      private: no
  tasks:
    - name: create dynamic docker container
      community.docker.docker_container:
        name: jcb_dynamic
        image: ubuntu:jammy
        ports:
          - "8081:8080"
        exposed_ports:
          - '8080'
        command: bash /run_dynamic.sh
        volumes:
          - ./run_container.sh:/run_dynamic.sh
          - ./volumes/jcb_dynamic/:/JCBDemo/
        env:
          NODES: "{{ node_count }}"
      become: yes
    - name: create static docker container
      community.docker.docker_container:
        name: jcb_static
        image: ubuntu:jammy
        ports:
          - "8080:8080"
        exposed_ports:
          - "8080"
        command: bash /run_static.sh
        volumes:
          - ./run_container.sh:/run_static.sh
          - ./volumes/jcb_static/:/JCBDemo/
      become: yes
