version: "3.9"
services:
  web:
    expose:
      - "8080"
    ports:
      - "127.0.0.1:8080:8080"
    image: "ubuntu:jammy"
    command: bash -c "/run_jcbdemo.sh"
    volumes:
      - ./jcb_main/:/JCBDemo/
      - ./run_jcbdemo.sh:/run_jcbdemo.sh
