version: "3.9"

#x-shared-repo:
#  &shared-repo
#  type: bind
#  source: ./jcb_main/
#  target: /JCBDemo/

services:
  dynamic:
    ports:
      - "8081:8080"
    expose:
      - "8080"
    image: "ubuntu:jammy"
    command: bash -c "/run_jcbdynamic.sh"
    volumes:
      - ./run_jcbdynamic.sh:/run_jcbdynamic.sh
      - ./config.ini:/config.ini
      - ./jcb_dynamic/:/JCBDemo/
#      - <<: *shared-repo
  static:
    ports:
      - "8080:8080"
    expose:
      - "8080"
    image: "ubuntu:jammy"
    command: bash -c "/run_jcbstatic.sh"
    volumes:
      - ./run_jcbstatic.sh:/run_jcbstatic.sh
      - ./jcb_static/:/JCBDemo/
#      - <<: *shared-repo
