version: "3.9"

services:
#  vars_prompt:
#    - name: nodes_count
#      prompt: enter desired amount of nodes
#      default: 1000
#      private: no
  dynamic:
    container_name: "jcb_dynamic"
    ports:
      - "8081:8080"
    expose:
      - "8080"
    image: "ubuntu:jammy"
  static:
    container_name: "jcb_static"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    image: "ubuntu:jammy"

